### ISSUE TITLE
Remove requirements.txt

### ISSUE THREAD

**Issue by impredicative** [LaunchpadAI/space-bandits#1]
Is the `requirements.txt` file necessary or can it be deleted? The requirements are already defined in `setup.py`?

**Comment by AlliedToasters** [comment]
@impredicative requirements.txt is here to help developers who want to contribute to the project build a dev environment. Certainly not necessary but nice to have both.

[see this answer](https://stackoverflow.com/questions/43658870/requirements-txt-vs-setup-py)

**Comment by impredicative** [comment]
It is not in sync with setup.py. Anyway, duplication of this specification will always risk being out of sync. Why not just read it from one place instead, i.e. from requirements.txt? Consider the answers [here](https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py).

**Comment by impredicative** [comment]
Your requirements.txt file will always fall out of sync. You don't really need it. It still says tensorflow!

Alternatively, use it, but read it in from setup.py. This is doable. The point is to have a singular definition of the requirements.

**Comment by AlliedToasters** [comment]
Ok @impredicative you're right, we've removed requirements.txt
