### ISSUE TITLE
Return the probabilities from Thompson sampling, not the max

### ISSUE THREAD

**Issue by amoderate84** [LaunchpadAI/space-bandits#13]
Many use-cases for bandits require optimizing a ux element such as a carousel or search results.  I want to use something like ranked bandit - so a separate bandit for each slot in a carousel.  However - to ensure that duplicate items are not displayed, if the first choice of an item is being displayed in slot 1, i need to remove it from the list for slot 2 and choose the next best one.

this is the [paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/11/kss_aaai2013.pdf) I am using as a reference

**Comment by AlliedToasters** [comment]
Hello @amoderate84,

There are a couple of things you can try with the current release (I won't have time to build new features this week, PR's are encouraged).

If you use the hidden method `model._sample(context)`, you will get the vector of all sampled actions as a numpy array.

You can try the `model.predict_proba(context)` method as well, which is appropriate only for binary outcomes. This should return an array in action space bounded by [0,1].

Hope this helps and I will either try to add new features or improve documentation in future releases.

**Comment by AlliedToasters** [comment]
Closing, please re-open if these solutions do not meet your requirements @amoderate84
