### ISSUE TITLE
Model can't be initialized in linear.py using fit() if not all actions have been observed at least once

### ISSUE THREAD

**Issue by balzac2000** [LaunchpadAI/space-bandits#20]
I was trying to use the `fit()` function to update a model with the rewards I got after issuing a batch of 100 actions. This was the first batch of actions that the model had issued and it was all the same action (because of [this bug](https://github.com/fellowship/space-bandits/issues/19), the `initial_pulls` parameter was ignored). However, I ran into an error and was unable to do so. After much digging, I found out that this only happened when I tried to fit the model with data that only had one action (if I passed a dataframe where each action was represented once, the problem didn't appear). 

Here's a reproducible example:
```
import numpy as np
import pandas as pd
from space_bandits import LinearBandits

np.random.seed(0)

model = LinearBandits(initial_pulls=2, num_actions=2, num_features=1)
model.fit(
    contexts=pd.DataFrame(np.random.normal(loc=10, size=100)),
    actions=np.array([0] * 100),  # replace with np.array([1] + [0] * 99) and it will work!
    rewards=np.random.normal(loc=10, size=100),
)
```
The output I get is:
```
Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "/Users/lucaslangwagen/.conda/envs/test/lib/python3.7/site-packages/space_bandits/linear.py", line 255, in fit
    self._update_action(action)
  File "/Users/lucaslangwagen/.conda/envs/test/lib/python3.7/site-packages/space_bandits/linear.py", line 218, in _update_action
    x, y = self.data_h.get_data(action)
  File "/Users/lucaslangwagen/.conda/envs/test/lib/python3.7/site-packages/space_bandits/contextual_dataset.py", line 158, in get_data
    return self.contexts[ind, :], self.rewards[ind, action]
IndexError: index 1 is out of bounds for dimension 1 with size 1
```

By using a debugger, I was able to find that the problem is in the `_ingest_data` method of `contextual_dataset.py`, specifically in this line:
`rewards_array = coo_matrix((np.array(rewards), (np.arange(data_length), np.array(actions)))).toarray()`
The result of this operation returns an array of shape `(data_length, len(actions.unique()))`. So then, if an action is not represented in the initial input `actions`, the resulting structure in the class attribute `self.rewards` of the `ContextualDataset` object will not have the same dimensions as it should (it should go by `num_actions`) and then the above error will arise when trying to execute `self.rewards[ind, action]` for one of the actions that wasn't represented.

I believe the code should be fixed so that we can fit a model with data even if one action is missing (that action's prior parameters should remain the defaults).

**Comment by AlliedToasters** [comment]
@lucaslangwagen thanks for diving into this. it sounds like you have a good understanding of the source of the issue. Please feel free to submit a pull request that solves the issue! This is a community and volunteer-maintained library so your contributions are greatly appreciated and needed!

**Comment by balzac2000** [comment]
After doing a workaround ion my code to avoid this bug, I encountered it once more and realized that my previous assumptions were not correct, as these reproducible examples show:

```
import numpy as np
import pandas as pd
from space_bandits import LinearBandits

np.random.seed(0)

model = LinearBandits(initial_pulls=2, num_actions=3, num_features=1)
model.fit(
    contexts=pd.DataFrame(np.random.normal(loc=10, size=100)),
    actions=np.array([2] + [0] * 99),
    # np.array([0] * 100) doesn't work
    # np.array([1] + [0] * 99) doesn't work
    # np.array([2] + [0] * 99) works
    rewards=np.random.normal(loc=10, size=100),
)
```

The problem still seems to be in the _ingest_data method of contextual_dataset.py, specifically in this line:
`rewards_array = coo_matrix((np.array(rewards), (np.arange(data_length), np.array(actions)))).toarray()`
but the result of this operation returns an array of shape `(data_length, np.max(actions.unique()))`, that's why with 3 actions, even if we miss one, as long as the maximum index is present the bug doesn't appear

**Comment by AlliedToasters** [comment]
@lucaslangwagen ,

Thanks for tracking this down. I took your snippet and created a new test case + patch in the code, which seems to have fixed the issue.

Please [review the changes here](https://github.com/LaunchpadAI/space-bandits/pull/22).

I will build a new release and push it to pypi if this fix solves your issue - thanks again!

**Comment by AlliedToasters** [comment]
@lucaslangwagen 
I've released a new patch that includes this change. Version >= 0.0.993 passes the test case you provided; you should get this version if you install directly via pip and pypi (`pip install space-bandits`). Closing!
