### ISSUE TITLE
Is project dead?

### ISSUE THREAD

**Issue by impredicative** [LaunchpadAI/space-bandits#4]
Please advise if the project is dead, so people can use something else that may be better maintained. No changes have been made to the repo in a while. The previously logged simple issues have been unattended.

**Comment by impredicative** [comment]
@AlliedToasters Perhaps you're not Watching this repo?

**Comment by AlliedToasters** [comment]
@impredicative indeed I have not been watching this repo since it was moved, apologies! I'll take a look at those issues now and start following. Thanks for pinging me!
