### ISSUE TITLE
Migrating to Pytorch?

### ISSUE THREAD

**Issue by AlliedToasters** [LaunchpadAI/space-bandits#5]
This library uses tensorflow but I'd like to migrate to torch before the project matures. Thoughts on adding pytorch as a dependency? (certainly easier to install than tensorflow!)

**Comment by impredicative** [comment]
To play devil's advocate, what are the reasons for wanting to migrate?

**Comment by AlliedToasters** [comment]
As of version 0.0.95, we're tensorflow-free. All deep learning functionality has been replaced by pytorch.

This is to simplify deployment and development.
