### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by impredicative** [LaunchpadAI/space-bandits#7]
`requirements.txt` seems out of date. `setup.py` seems to have a newer list. `requirements.txt` should probably be brought up to date; it currently even has an invalid entry "cbandits".

I think it's crazy enough that the requirements specification is duplicated, but at least it should be correct.

**Comment by AlliedToasters** [comment]
Fixed, thanks

**Comment by impredicative** [comment]
Is it really fixed? `requirements.txt` and `setup.py` note a different number of requirements, so how can both be correct? I'm looking at the `master` branch.

**Comment by AlliedToasters** [comment]
fixed
