### ISSUE TITLE
Space-Bandit toy problem

### ISSUE THREAD

**Issue by drdanialrusdi** [LaunchpadAI/space-bandits#8]
When trying the below code which thompson are set to true, it is produce the error like at the bottom one. Thompson =False have no problem

plot_decision_boundary(linear_model, X, Y, h=.5, thompson=True, parallelize=True, n_threads=3, title='Decision Boundary With Thompson Sampling')

RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\00130161\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\00130161\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\00130161\AppData\Local\Continuum\anaconda3\lib\site-packages\space_bandits\linear.py", line 27, in get_mn
    mu = mus[i]
TypeError: 'NoneType' object is not subscriptable
"""

**Comment by AlliedToasters** [comment]
This is a weird issue, but to be honest, `plot_decision_boundary` is not a part of the library, it's just an example function written for the toy problem. As a quick fix, try passing `parallelize=False` . That may fix it, but at the cost of taking longer to run the function.

I'll need more information about your model to properly debug the code. Is your model fit prior to running the above code? Could you possibly provide all of your code so I can reproduce the error locally? Are you able to run the toy_problem.ipynb notebook without issue? Let me know.

**Comment by AlliedToasters** [comment]
Closing issue due to lack of information and inactivity.

**Comment by MahdiGhiasi** [comment]
I'm observing the same issue running toy_problem.ipynb, and I can confirm that passing `parallelize=False` does indeed solve the problem.

I'm running the toy problem on Anaconda on Windows 10, Python 3.7.1, Torch 1.4.0 CPU and Space Bandits 0.0.992.
