### ISSUE TITLE
Rename PyPI package to spacebandits

### ISSUE THREAD

**Issue by impredicative** [LaunchpadAI/space-bandits#9]
@AlliedToasters Having a hyphen or underscore makes for a confusing PyPI package name due to their mix-up. I recommend deleting the current `space_bandits` package on PyPI and publishing it as `spacebandits` without any hyphen or underscore.

I speak from experience here. There is already enough confusion with needing to install as `pip install space-bandits` when PyPI lists it as `space_bandits`.

Of course this will require updating `README.md` and `setup.py` first.

**Comment by AlliedToasters** [comment]
Thanks for your opinion, I will consider it.
